# -*- coding: utf-8 -*-
"""hw1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vkS1kQEpqoHCpV7ftbIEPxbvi_HRnHI
"""

Input = int(input("請輸入 0 到 255 之間的數字: "))
# 轉換為二進位
a7 = Input // 128
Input = Input - a7 * 128
a6 = Input // 64
Input = Input - a6 * 64
a5 = Input // 32
Input = Input - a5 * 32
a4 = Input // 16
Input = Input - a4 * 16
a3 = Input // 8
Input = Input - a3 * 8
a2 = Input // 4
Input = Input - a2 * 4
a1 = Input // 2
Input = Input - a1 * 2
a0 = Input
# 把二進位數字存到列表中
binary_digits = [a7, a6, a5, a4, a3, a2, a1, a0]
# 去掉前導0，輸出二進位
found_first_one = False
for digit in binary_digits:
    if digit == 1:
        found_first_one = True
    if found_first_one:
        print(digit, end='')
# 特殊情況：輸入0
if not found_first_one:
    print(0)
print(", ",end="")

#轉換為十六進位
# 16 進位的高位 (前 4 位)
A1 = a7 * 8 + a6 * 4 + a5 * 2 + a4
# 16 進位的低位 (後 4 位)
A2 = a3 * 8 + a2 * 4 + a1 * 2 + a0
# 將 10~15 轉成 A~F
if A1 == 10:
    A1 = 'A'
elif A1 == 11:
    A1 = 'B'
elif A1 == 12:
    A1 = 'C'
elif A1 == 13:
    A1 = 'D'
elif A1 == 14:
    A1 = 'E'
elif A1 == 15:
    A1 = 'F'

if A2 == 10:
    A2 = 'A'
elif A2 == 11:
    A2 = 'B'
elif A2 == 12:
    A2 = 'C'
elif A2 == 13:
    A2 = 'D'
elif A2 == 14:
    A2 = 'E'
elif A2 == 15:
    A2 = 'F'
# 去掉十六進位前導0
if A1 == 0:
    print(A2)
else:
    print(A1, A2, sep='')